* update ndk * armv4t support
git-svn-id: http://csipsimple.googlecode.com/svn/trunk@252 9f815046-5998-e9c0-b7e2-ac03a23edfa4

diff --git a/pjsip_android/ndk-gdb b/pjsip_android/ndk-gdb
--- a/pjsip_android/ndk-gdb
+++ b/pjsip_android/ndk-gdb
@@ -83,6 +83,26 @@ run_awk_manifest_script ()
     $AWK_CMD -f $AWK_SCRIPTS/$1 $PROJECT/$MANIFEST
 }
 
+if [ "$HOST_OS" = "cygwin" ] ; then
+# Return native path representation from cygwin one
+# $1: a cygwin-compatible path (e.g. /cygdrive/c/some/thing)
+# Return: path in host windows representation, e.g. C:/some/thing
+#
+# We use mixed mode (i.e. / as the directory separator) because
+# all the tools we use recognize it properly, and it avoids lots
+# of escaping nonsense associated with "\"
+#
+native_path ()
+{
+    cygpath -m $1
+}
+else # HOST_OS != windows
+native_path ()
+{
+    echo "$1"
+}
+fi # HOST_OS != windows
+
 VERBOSE=no
 while [ -n "$1" ]; do
     opt="$1"
@@ -234,6 +254,15 @@ log "ADB version found: $ADB_VERSION"
 ADB_CMD="${ADB_CMD}${ADB_FLAGS}"
 log "Using final ADB command: '$ADB_CMD'"
 
+adb_shell ()
+{
+    # Run an adb shell command and return its output.
+    #
+    # We need to filter weird control characters like \r that are
+    # included in the output.
+    #
+    $ADB_CMD shell $@ | sed -e 's![[:cntrl:]]!!g'
+}
 
 # Check the awk tool
 AWK_SCRIPTS=$ANDROID_NDK_ROOT/build/awk
@@ -323,24 +352,45 @@ if [ $? != 0 ] ; then
     exit 1
 fi
 
+# Check that the device is running Froyo (API Level 8) or higher
+#
+API_LEVEL=`adb_shell getprop ro.build.version.sdk`
+if [ $? != 0 -o -z "$API_LEVEL" ] ; then
+    echo "ERROR: Could not find target device's supported API level !"
+    echo "ndk-gdb will only work if your device is running Android 2.2 or higher."
+    exit 1
+fi
+log "Device API Level: $API_LEVEL"
+if [ "$API_LEVEL" -lt "8" ] ; then
+    echo "ERROR: ndk-gdb requires a target device running Android 2.2 (API level 8) or higher."
+    echo "The target device is running API level $API_LEVEL !"
+    exit 1
+fi
+
 # Get the target device's supported ABI(s)
 # And check that they are supported by the application
 #
 COMPAT_ABI=none
-CPU_ABI=`$ADB_CMD shell getprop ro.product.cpu.abi | sed -e 's!\\r!!g'`
-echo "$APP_ABIS" | grep -q -F "$CPU_ABI"
-if [ $? = 0 ] ; then
-    COMPAT_ABI=$CPU_ABI
-fi
+CPU_ABI=`adb_shell getprop ro.product.cpu.abi`
+for ABI in $APP_ABIS; do
+    if [ "$ABI" = "$CPU_ABI" ] ; then
+        COMPAT_ABI=$CPU_ABI
+        break
+    fi
+done
 
-CPU_ABI2=`$ADB_CMD shell getprop ro.product.cpu.abi2 | sed -e 's!\\r!!g'`
+CPU_ABI2=`adb_shell getprop ro.product.cpu.abi2`
 if [ -z "$CPU_ABI2" ] ; then
     log "Device CPU ABI: $CPU_ABI"
 else
     log "Device CPU ABIs: $CPU_ABI $CPU_ABI2"
-    echo "$APP_ABIS" | grep -q -F "$CPU_ABI2"
-    if [ $? = 0 ] ; then
-        COMPAT_ABI=$CPU_ABI2
+    if [ "$COMPAT_ABI" = "none" ] ; then
+        for ABI in $APP_ABIS; do
+            if [ "$ABI" = "$CPU_ABI2" ] ; then
+                COMPAT_ABI=$CPU_ABI2
+                break
+            fi
+        done
     fi
 fi
 if [ "$COMPAT_ABI" = none ] ; then
@@ -368,7 +418,7 @@ fi
 # Let's check that 'gdbserver' is properly installed on the device too. If this
 # is not the case, the user didn't install the proper package after rebuilding.
 #
-DEVICE_GDBSERVER=`$ADB_CMD shell ls /data/data/$PACKAGE_NAME/lib/gdbserver`
+DEVICE_GDBSERVER=`adb_shell ls /data/data/$PACKAGE_NAME/lib/gdbserver`
 log "Found device gdbserver: $DEVICE_GDBSERVER"
 if pattern_match "No such file or directory" "$DEVICE_GDBSERVER" ] ; then
     echo "ERROR: Non-debuggable application installed on the target device."
@@ -387,11 +437,9 @@ APP_OUT=`get_build_var_for_abi TARGET_OUT $COMPAT_ABI`
 log "Using app out directory: $APP_OUT"
 
 # Find the <dataDir> of the package on the device
-DATA_DIR=`$ADB_CMD shell run-as $PACKAGE_NAME /system/bin/sh -c pwd`
-# mmm, a rogue \r at the end, get rid of it.
-DATA_DIR=`echo "$DATA_DIR" | sed -e 's!\\r!!g'`
+DATA_DIR=`adb_shell run-as $PACKAGE_NAME /system/bin/sh -c pwd`
 log "Found data directory: '$DATA_DIR'"
-if [ $? != 0 ] ; then
+if [ $? != 0 -o -z "$DATA_DIR" ] ; then
     echo "ERROR: Could not extract package's data directory. Are you sure that"
     echo "       your installed application is debuggable?"
     exit 1
@@ -485,7 +533,7 @@ fi
 
 # Get the app_server binary from the device
 APP_PROCESS=$APP_OUT/app_process
-run adb pull /system/bin/app_process $APP_PROCESS
+run $ADB_CMD pull /system/bin/app_process `native_path $APP_PROCESS`
 log "Pulled $APP_BINARY from device/emulator."
 
 # Now launch the appropriate gdb client with the right init commands
